# Numpy

In [1]:
# Numpy introduction : Numpy is a fundamental library for scientific computin in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.
import numpy as np

# pip install numpy

In [2]:
!pip install numpy

In [ ]:
# Create array using numpy
# create a 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape) # shape function gives the dimension of the array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8])
print(arr2.reshape(2,4))  # reshape function is used to change the shape of the array
print(arr2.reshape(2,2,2))  
arr2.reshape(2,2,2)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
arr2 = np.array([[1,2,3,4,5,6,7]])
print(arr2)

[[1 2 3 4 5 6 7]]


In [6]:
arr2 = np.array([[1,2,3,4,5],[2,3,45,9,8]])
print(arr2)

[[ 1  2  3  4  5]
 [ 2  3 45  9  8]]


In [ ]:
np.arange(0,10,2).reshape(5,1) # arange function is used to create an array with a range of values

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [30]:
np.ones((3,4)) # ones function is used to create an array of ones with given shape
print(np.ones((3,4)))
np.zeros((2,3)) # zeros function is used to create an array of zeros with given shape
print(np.zeros((2,3)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Identity matrix
# eye function is used to create an identity matrix of given size

np.eye(4)  # 4x4 identity matrix
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)  # number of dimensions
print("Size:",arr.size)  # total number of elements in the array
print("Data type:",arr.dtype)  # data type of elements in the array
print("Item size:",arr.itemsize)  # size of each element in bytes
print("Total bytes:",arr.nbytes)  # total size of the array in bytes (itemsize * size)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64
Item size: 8
Total bytes: 72


In [11]:
# Numpy Vectorized Operations

arr1 = np.array([100,2,3,400,5])
arr2 = np.array([10,20,30,40,50])

# Element-wise addition
print("Addition:", arr1 + arr2)
# Element-wise subtraction
print("Subtraction:", arr2 - arr1)
# Element-wise multiplication
print("Multiplication:", arr1 * arr2)
# Element-wise division
print("Division:", arr2 / arr1)
# Element-wise square
print("Square of arr1:", arr1 ** 2)
# Element-wise square root
print("Square root of arr2:", np.sqrt(arr2))
# Element-wise exponential
print("Exponential of arr1:", np.exp(arr1))
# Element-wise logarithm
print("Logarithm of arr2:", np.log(arr2))
# Element-wise sine
print("Sine of arr1:", np.sin(arr1))
# Element-wise cosine
print("Cosine of arr1:", np.cos(arr1))
# Element-wise tangent
print("Tangent of arr1:", np.tan(arr1))
# Element-wise maximum
print("Element-wise maximum:", np.maximum(arr1, arr2))
# Element-wise minimum
print("Element-wise minimum:", np.minimum(arr1, arr2))
# Dot product
print("Dot product:", np.dot(arr1, arr2))
# Sum of all elements
print("Sum of arr1:", np.sum(arr1))
print("Sum of arr2:", np.sum(arr2))
# Mean of all elements
print("Mean of arr1:", np.mean(arr1))
print("Mean of arr2:", np.mean(arr2))

Addition: [110  22  33 440  55]
Subtraction: [ -90   18   27 -360   45]
Multiplication: [ 1000    40    90 16000   250]
Division: [ 0.1 10.  10.   0.1 10. ]
Square of arr1: [ 10000      4      9 160000     25]
Square root of arr2: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential of arr1: [2.68811714e+043 7.38905610e+000 2.00855369e+001 5.22146969e+173
 1.48413159e+002]
Logarithm of arr2: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Sine of arr1: [-0.50636564  0.90929743  0.14112001 -0.85091936 -0.95892427]
Cosine of arr1: [ 0.86231887 -0.41614684 -0.9899925  -0.52529634  0.28366219]
Tangent of arr1: [-0.58721392 -2.18503986 -0.14254654  1.61988443 -3.38051501]
Element-wise maximum: [100  20  30 400  50]
Element-wise minimum: [10  2  3 40  5]
Dot product: 17380
Sum of arr1: 510
Sum of arr2: 150
Mean of arr1: 102.0
Mean of arr2: 30.0


In [12]:
# Array Indexing and Slicing

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print("Original Array:\n", arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
arr[0][0]  # Accessing first element (1)
print("Element at (0,0):", arr[0][0])

Element at (0,0): 1


In [14]:
arr[1:,2:]  # Slicing from second row and third column to the end
print("Sliced Array from (1,2) to end:\n", arr[1:,2:])

Sliced Array from (1,2) to end:
 [[ 7  8]
 [11 12]]


In [15]:
print(arr[1:3,1:3])  # Slicing from second row and second column to third row and third column

[[ 6  7]
 [10 11]]


In [16]:
# Modify array element

arr[0][0] = 100
print("Modified Array:\n", arr)

Modified Array:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [17]:
arr[1:]=200

In [18]:
arr

array([[100,   2,   3,   4],
       [200, 200, 200, 200],
       [200, 200, 200, 200]])

In [31]:
# Statistical  concepts using Numpy -- Normalization, Standardization, to have mean 0 and standard deviation 1

data = np.array([1,2,3,4])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [32]:
# Mean
mean = np.mean(data)
print("Mean:", mean)
# Median
median = np.median(data)
print("Median:", median)
# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)
# Variance
var = np.var(data)
print("Variance:", var)

Mean: 2.5
Median: 2.5
Standard Deviation: 1.118033988749895
Variance: 1.25


In [33]:
data1 = np.array([1,2,3,4])

data1>3

array([False, False, False,  True])

In [34]:
data1[data1>3]  # Filtering elements greater than 5

array([4])

In [35]:
data1[(data1>3) & (data1<4)]  # Elements greater than 3 and less than 8

array([], dtype=int64)